In [3]:
import numpy as np

In [5]:
arr = np.arange(1, 21)

# a. calculations
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))


Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


In [7]:
# b. indices > 10
indices = np.where(arr > 10)
print("Indices where elements > 10:", indices)

Indices where elements > 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


In [8]:
arr2 = np.arange(1, 17).reshape(4, 4)

# a. print
print("2D Array:\n", arr2)

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [9]:
# b. transpose
print("Transpose:\n", arr2.T)

Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [10]:
# c. row & column sum
print("Row-wise sum:", np.sum(arr2, axis=1))
print("Column-wise sum:", np.sum(arr2, axis=0))

Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


In [11]:
a = np.random.randint(1, 21, (3, 3))
b = np.random.randint(1, 21, (3, 3))

print("Array A:\n", a)
print("Array B:\n", b)

Array A:
 [[12 20 15]
 [ 7 10  5]
 [11 17 12]]
Array B:
 [[ 1  1 12]
 [15 18  9]
 [18  7 15]]


In [12]:
# a. operations
print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)

Addition:
 [[13 21 27]
 [22 28 14]
 [29 24 27]]
Subtraction:
 [[11 19  3]
 [-8 -8 -4]
 [-7 10 -3]]
Multiplication:
 [[ 12  20 180]
 [105 180  45]
 [198 119 180]]


In [13]:
# b. dot product
print("Dot Product:\n", np.dot(a, b))

Dot Product:
 [[582 477 549]
 [247 222 249]
 [482 401 465]]


In [14]:
arr3 = np.arange(1, 13)


In [15]:
reshaped = arr3.reshape(3, 4)
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
# slicing
result = reshaped[:2, -2:]
print("Sliced (first 2 rows, last 2 columns):\n", result)

Sliced (first 2 rows, last 2 columns):
 [[3 4]
 [7 8]]
